# Generated by Django 6.0.3 on 2026-05-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('completada', models.BooleanField(default=False, help_text='la tarea se ha completada o no', verbose_name='FINALIZADA')),
                ('fecha_completada', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, help_text='Verdadero si NO esta archivada la tarea ')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='card_image/')),
                ('etiquetas', models.ManyToManyField(blank=True, default=None, null=True, related_name='etiquetas', to='todolist.etiqueta')),
            ],
            options={
                'verbose_name': 'Tareas de proyecto',
                'verbose_name_plural': 'Tareas de los proyectos',
                'ordering': ['-id'],
            },
        ),
    ]
