# Generated by Django 6.0.3 on 2026-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
