# Generated by Django 6.0.3 on 2026-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_tarea_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='etiquetas', to='todolist.etiqueta'),
        ),
    ]
