# Generated by Django 6.0.3 on 2026-04-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_etiqueta_tarea_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='activo',
            field=models.BooleanField(default=True, help_text='Verdadero si NO esta archivada la tarea '),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False, help_text='la tarea se ha completada o no', verbose_name='FINALIZADA'),
        ),
    ]
